name: bloc_concurrency_ext
description: Some additional bloc event transformers
version: 1.0.0
repository: https://github.com/mase7569/bloc_concurrency_ext

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7
  stream_transform: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
